name: 学習サイト
description: 学習サイト（atlasez.org）のIssue
title: ""
labels:
  - site:learning
body:
  - type: textarea
    id: summary
    attributes:
      label: 内容
      description: 発生している問題や提案を具体的に記載してください。
    validations:
      required: true
